stages:
- name: compile
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: ./mvnw clean package
- name: create image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: fortune-demo:${CICD_EXECUTION_SEQUENCE}
- name: deploy app
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:library-redis
      version: 9.0.2
      answers:
        password: topsecret
      name: redis
      targetNamespace: default
  - applyYamlConfig:
      path: ./k8s.yml
timeout: 5
branch: {}
notification: {}
