stages:
- name: Stage
  steps:
  - runScriptConfig:
      image: maven:3-jdk-8-slim
      shellScript: mvn package
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: azwickey/demo
      registry: 127.0.0.1:34886
timeout: 20
notification: {}
