---
apiVersion: v1
kind: Service
metadata:
  name: fortune-service
  labels:
    app: fortune-service
spec:
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: fortune-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fortune-app
  template:
    metadata:
      name: fortune-app
      labels:
        app: fortune-app
    spec:
      containers:
      - image: azwickey/fortune-demo:latest
        name: fortune-app
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: SPRING_REDIS_HOST
          value: "redis.default.svc.cluster.local"
