---
apiVersion: v1
kind: Service
metadata:
  name: fortune-service
  labels:
    app: fortune-service
spec:
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
  selector:
    app: fortune-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-app
  annotations:
    prometheus.io/path: '/actuator/prometheus'
    prometheus.io/port: '8080'
    prometheus.io/scrape: 'true'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fortune-app
  template:
    metadata:
      name: fortune-app
      labels:
        app: fortune-app
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        name: fortune-app
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: SPRING_REDIS_HOST
          value: "redis"
