spring:
  application:
    name: fortune
management:
  cloudfoundry:
    skip-ssl-validation: true
  security:
    enabled: false
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
---
spring:
  profiles: cloud